stages:
  get_features:
    cmd: python3 scripts/data_processing/get_features.py datasets/raw/cars.csv datasets/features/cars.csv
    deps:
    - datasets/raw/cars.csv
    - scripts/data_processing/get_features.py
    outs:
    - datasets/features/cars.csv
  prepare:
    cmd: python3 scripts/data_processing/change_text_to_numeric.py datasets/features/cars.csv
      datasets/prepared/cars.csv
    deps:
    - datasets/features/cars.csv
    - scripts/data_processing/change_text_to_numeric.py
    outs:
    - datasets/prepared/cars.csv
  train:
    cmd: python3 scripts/model_learning/dt.py datasets/prepared/cars.csv model.pkl
    deps:
    - datasets/prepared/cars.csv
    - scripts/model_learning/dt.py
    params:
    - train.max_depth
    - train.seed
    outs:
    - model.pkl
